# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8674c730a785cd78d3c0f499a0a78bfa79e392a1030e5320f8486d83cb7e7ebe6c61a6d421fa1e22c154257a8ac938c902cabccb8398df6374a4cfc26041c201

test:
  secret_key_base: 37726a0d1a4c16c151c07b3f436957cd048631efa80c5e79b2ebec45d9c7d6f87ce738dcff890d53226d7639eeab11f85d5fc3fbe275eb7d0e27b7f7caf6b6cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
